spring.application.name=empleos-backend

spring.data.mongodb.uri=mongodb+srv://dmaflafigueroa2_db_user:F6JN7YC6p3e7AYXC@bolsadetrabajo.1ktbt6v.mongodb.net/bolsaDeTrabajo?retryWrites=true&w=majority
spring.data.mongodb.database=bolsaDeTrabajo
server.port=8080